### ISSUE TITLE
Bindle server error (1)

### ISSUE THREAD

**Issue by radu-matei** [fermyon/autobindle#10]
I get the following error trying to start Bindle in a new environment:

```
[2022-02-23 10:10:50.516] [exthost] [error] Canceled: Canceled
    at Object.F [as canceled] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:5:1172)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:9076
    at Array.forEach (<anonymous>)
    at i.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:9024)
    at p.terminate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:102:694)
    at s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:112:36409)
    at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:112:34061)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12) autobindle.stop {"value":"fermyon.autobindle","_lower":"fermyon.autobindle"}
```

**Comment by radu-matei** [comment]
Deleting the data from the existing environments seems to have worked around the issue.

**Comment by radu-matei** [comment]
Never encountered this error again, closing.
